{% set name = "idds-doma" %}
{% set version = "0.10.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 529e1ec5971eeb06a40c7b00bc75980bd4c9f603add0fb738c969d1d814face9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - panda-client
    - python >=3.6

test:
  imports:
    - idds
    - idds.doma

about:
  home: https://pypi.org/project/idds-doma/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
