{% set name = "idds-doma" %}
{% set name_pypi = "idds_doma" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: 59a8f3d9351c2d30a1fc2ceade602ef414045a0bbc092995c74d036c5e982c85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - panda-client
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.doma

about:
  home: https://pypi.org/project/idds-doma/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
