{% set name = "idds-doma" %}
{% set name_pypi = "idds_doma" %}
{% set version = "2.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: 75ecb370cccc59cebc94884aec89790a37b1cda2aa92610e1fdf8192b14d03ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - panda-client
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.doma

about:
  home: https://pypi.org/project/idds-doma/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
