{% set name = "idds-doma" %}
{% set version = "0.7.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/idds-doma-{{ version }}.tar.gz
  sha256: 9d2c942b84c57f2417352b1d56966f2ff07908fbe77c98228c775e5e76dc9cd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - panda-client
    - python >=3.6

test:
  imports:
    - idds
    - idds.doma

about:
  home: https://pypi.org/project/idds-doma/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - yesw2000
